---
- hosts: localhost
  collections:
    - community.kubernetes
    - community.general

  pre_tasks:
    - name: Look for default defined cluster variables
      include_vars: ../vars/cluster.yml
      when: cluster_included is not defined or not cluster_included

    - fail:
        msg: Unable to continue without cluster variables set
      when: cluster_included is not defined or not cluster_included

  tasks:
    - include_role:
        name: openshift-installer
      when:
      - deploy_cluster|default(true)
      - cluster_name != "crc"
    - include_role:
        name: cluster-adjuster
    - include_role:
        name: pull-secret
      when:
      - apply_tbr_secret|default(true)
      - terms_based_registry_pull_secret is defined
      - terms_based_registry_pull_secret != "eyJhdXRocyI6eyJyZWdpc3RyeS5yZWRoYXQuaW8iOnsiYXV0aCI6"
    - include_role:
        name: redhatgov-catalog
      when:
      - deploy_catalog|default(true)
    - include_role:
        name: ocs
      when:
      - deploy_ocs|default(true)
      - cluster_name != "crc"
